"use strict";
const fs=require("fs"),path=require("path");
const p=path.join(__dirname,"index.js");
let s=fs.readFileSync(p,"utf8");
function between(a,start,end,repl){const i=a.indexOf(start),j=a.indexOf(end,i+start.length);if(i<0||j<0)throw Error("marker missing: "+start);return a.slice(0,i)+repl+a.slice(j);}
function fn(a,name,repl){const m=new RegExp("function\\s+"+name+"\\s*\\(").exec(a);if(!m)throw Error("function missing: "+name);const o=a.indexOf("{",m.index);let d=0,q=null,e=false,lc=false,bc=false;for(let i=o;i<a.length;i++){const c=a[i],n=a[i+1];if(lc){if(c==="\n")lc=false;continue}if(bc){if(c==="*"&&n==="/"){bc=false;i++}continue}if(q){if(e){e=false;continue}if(c==="\\"){e=true;continue}if(c===q)q=null;continue}if(c==="/"&&n==="/"){lc=true;i++;continue}if(c==="/"&&n==="*"){bc=true;i++;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==="{")d++;else if(c==="}"&&--d===0)return a.slice(0,m.index)+repl+a.slice(i+1)}throw Error("unclosed function: "+name)}
s=s.replace(/shark_v1_edit/g,"kontext_pro_edit").replace(/sharkV1EditPipeline/g,"kontextProEditPipeline").replace(/fal-ai\/flux\/dev\/image-to-image/g,"fal-ai/flux-pro/kontext").replace(/\/shark/g,"/edit").replace(/cmdShark/g,"cmdEdit").replace(/SHARK V1/g,"PIXLEMETA EDIT").replace(/🦈/g,"✏️").replace(/shark/g,"edit");
const models="const MODELS = {cinematic:{key:\"cinematic\",label:\"🎬 Pixlemeta Cinematic\",type:\"t2i\",qualities:{\"2k\":{cost:2},\"4k\":{cost:4}},engines:{primary:\"fal_schnell\",backup:null}},realism:{key:\"realism\",label:\"📸 Pixlemeta Realism (DSLR)\",type:\"t2i\",qualities:{\"2k\":{cost:6},\"4k\":{cost:15}},engines:{primary:\"fal_flux_ultra_realism\",backup:\"replicate_sdxl\"}},ultra8k:{key:\"ultra8k\",label:\"🟪 Pixlemeta Ultra 8K (True)\",type:\"t2i\",qualities:{\"8k\":{cost:30}},engines:{primary:\"fal_flux_pro_8k\",backup:null}},edit:{key:\"edit\",label:\"✏️ Pixlemeta EDIT (FLUX.1 Kontext Pro)\",type:\"i2i\",qualities:{\"2k\":{cost:15},\"4k\":{cost:25},\"8k\":{cost:45}},engines:{primary:\"kontext_pro_edit\",backup:null}},seedream4:{key:\"seedream4\",label:\"🌱 Seedream 4.0\",type:\"t2i\",qualities:{\"2k\":{cost:6},\"4k\":{cost:12}},engines:{primary:\"fal_seedream4\",backup:null}},fluxdev:{key:\"fluxdev\",label:\"⚡ FLUX.1 [dev]\",type:\"t2i\",qualities:{\"2k\":{cost:4}},engines:{primary:\"fal_flux_dev\",backup:null}},gptimage2:{key:\"gptimage2\",label:\"🧠 GPT Image 2\",type:\"t2i\",qualities:{\"2k\":{cost:25},\"4k\":{cost:50}},engines:{primary:\"fal_gpt_image2\",backup:null}},nano2:{key:\"nano2\",label:\"🍌 Nano Banana 2\",type:\"t2i\",qualities:{\"2k\":{cost:8},\"4k\":{cost:16}},engines:{primary:\"coming_soon\",backup:null}},nanop:{key:\"nanop\",label:\"🍌 Nano Banana Pro\",type:\"t2i\",qualities:{\"2k\":{cost:12},\"4k\":{cost:24}},engines:{primary:\"coming_soon\",backup:null}}};const PLAN_ACCESS={trial:new Set([\"cinematic\",\"realism\",\"seedream4\",\"fluxdev\"]),promo:new Set([\"cinematic\",\"realism\",\"edit\",\"seedream4\",\"fluxdev\",\"gptimage2\"]),paid:new Set(Object.keys(MODELS)),admin:new Set(Object.keys(MODELS))};";
s=between(s,"const MODELS = {","/* =========================\n   ASPECT RATIOS\n========================= */",models+"\n\n/* =========================\n   ASPECT RATIOS\n========================= */");
const fal="async function falSeedream4Generate(prompt,q,r){const a=getRatio(r),d=await falRun(\"fal-ai/bytedance/seedream/v4/text-to-image\",{prompt,image_size:{width:a.width,height:a.height},num_images:1}),url=pickFirstImageUrl(d);if(!url)throw Error(\"Seedream 4.0 returned no image\");return {url,type:\"image\",ratio:a.label}}\nasync function falFluxDevGenerate(prompt,q,r){const d=await falRun(\"fal-ai/flux/dev\",{prompt,num_images:1,output_format:\"jpeg\"}),url=pickFirstImageUrl(d);if(!url)throw Error(\"FLUX.1 [dev] returned no image\");return {url,type:\"image\",ratio:getRatio(r).label}}\nasync function falGPTImage2Generate(prompt,q,r){const a=getRatio(r),quality=q===\"4k\"?\"high\":\"medium\",d=await falRun(\"openai/gpt-image-2\",{prompt,image_size:{width:a.width,height:a.height},quality,n:1}),url=pickFirstImageUrl(d);if(!url)throw Error(\"GPT Image 2 returned no image\");return {url,type:\"image\",ratio:a.label}}\n";
if(!s.includes("falSeedream4Generate")){const mark="/* =========================\n   ENGINE ROUTER\n========================= */";if(s.includes(mark))s=s.replace(mark,fal+mark)}
if(!s.includes('case "fal_seedream4"'))s=s.replace("  switch (engine) {","  switch (engine) {\n    case \"fal_seedream4\": return falSeedream4Generate(prompt,qualityKey,ratioKey);\n    case \"fal_flux_dev\": return falFluxDevGenerate(prompt,qualityKey,ratioKey);\n    case \"fal_gpt_image2\": return falGPTImage2Generate(prompt,qualityKey,ratioKey);");
s=fn(s,"imageKeyboard",`function imageKeyboard(){return {inline_keyboard:[[{text:"🎬 Cinematic",callback_data:"m:cinematic"},{text:"📸 Realism",callback_data:"m:realism"}],[{text:"🟪 Ultra 8K",callback_data:"m:ultra8k"},{text:"✏️ EDIT",callback_data:"m:edit"}],[{text:"🌱 Seedream 4.0",callback_data:"m:seedream4"},{text:"⚡ FLUX.1 [dev]",callback_data:"m:fluxdev"}],[{text:"🧠 GPT Image 2",callback_data:"m:gptimage2"}],[{text:"🍌 Nano Banana 2 • SOON",callback_data:"soon:nano2"},{text:"🍌 Nano Banana Pro • SOON",callback_data:"soon:nanop"}],[{text:"⬅️ Back",callback_data:"x:home"},{text:"❌ Cancel",callback_data:"x:cancel"}]]};}`);
s=fn(s,"videoKeyboard",`function videoKeyboard(){return {inline_keyboard:[[{text:"⚡ Wan 2.2 • COMING SOON",callback_data:"v:soon:wan22"}],[{text:"🎞️ LTX-2 • COMING SOON",callback_data:"v:soon:ltx2"}],[{text:"🎥 Kling 3.0 • COMING SOON",callback_data:"v:soon:kling3"}],[{text:"🌊 Wan 2.7 • COMING SOON",callback_data:"v:soon:wan27"}],[{text:"🚀 Seedance 2.0 Fast • COMING SOON",callback_data:"v:soon:seedance20fast"}],[{text:"🎬 Seedance 2.0 • COMING SOON",callback_data:"v:soon:seedance20"}],[{text:"🔥 Seedance 2.5 • COMING SOON",callback_data:"v:soon:seedance25"}],[{text:"✨ Gemini Omni 1.1 Flash • COMING SOON",callback_data:"v:soon:geminiomni"}],[{text:"🎥 Veo 3.1 • COMING SOON",callback_data:"v:soon:veo31"}],[{text:"⚡ Kling 3.0 Turbo Pro • COMING SOON",callback_data:"v:soon:kling3turbo"}],[{text:"⚙️ Video Settings • COMING SOON",callback_data:"v:settings"}],[{text:"⬅️ Back",callback_data:"x:home"}]]};}`);
s=fn(s,"showVideoMenu",`async function showVideoMenu(chatId,userId){await clearFlow(userId);return sendMessage(chatId,"🎬 PIXELMETA VIDEO STUDIO\\n\\nVideo models are being integrated next.\\n\\n🎛️ Planned controls\\n• Quality: 480p / 580p / 720p / 1080p / 4K\\n• Duration: 5s / 8s / 10s / 15s\\n• FPS: 24 / 30\\n• Audio: On / Off\\n• Ratio: 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9\\n\\n🚧 No video credits are consumed until a model is actually connected.",{reply_markup:videoKeyboard()});}`);
s=fn(s,"cmdModels",`async function cmdModels(chatId,userId){const plan=await getPlan(userId);const lines=["📚 PIXELMETA AI — MODEL STUDIO","","🖼️ IMAGE — LIVE TODAY (FAL)","🎬 Cinematic • 2K 2c / 4K 4c","📸 Realism • 2K 6c / 4K 15c","🟪 Ultra 8K • 8K 30c","✏️ EDIT • FLUX.1 Kontext Pro • 2K 15c / 4K 25c / 8K 45c","🌱 Seedream 4.0 • 2K 6c / 4K 12c","⚡ FLUX.1 [dev] • 2K 4c","🧠 GPT Image 2 • 2K 25c / 4K 50c","","🍌 IMAGE — WAVESPEED NEXT","Nano Banana 2 • Coming soon","Nano Banana Pro • Coming soon","","🎬 VIDEO — COMING SOON","Wan 2.2 • LTX-2 • Kling 3.0 • Wan 2.7","Seedance 2.0 Fast • Seedance 2.0 • Seedance 2.5","Gemini Omni 1.1 Flash • Veo 3.1 • Kling 3.0 Turbo Pro","","Your plan: "+plan.toUpperCase()];return sendMessage(chatId,lines.join("\\n"),{reply_markup:homeKeyboard()});}`);
if(!s.includes('data.startsWith("soon:")'))s=s.replace('  if (data.startsWith("m:")) {','  if (data.startsWith("soon:") || data.startsWith("v:soon:")) { return sendMessage(chatId,"🚧 COMING SOON\\n\\nThis model is listed in the Studio but is not connected yet.\\n\\nNo credits were charged."); }\n\n  if (data.startsWith("m:")) {');
if(!s.includes('engine === "coming_soon"'))s=s.replace('  const primary =\n    model.engines.primary;','  const primary =\n    model.engines.primary;\n    if (primary === "coming_soon") throw new Error("This model is coming soon");');
fs.writeFileSync(p,s,"utf8");console.log("PIXLEMETA bootfix applied");require(p);
